backend:
  name: github
  repo: gabonidev/gabonidev.github.io   # Path to your Github/Gitlab repository
  branch: main # Branch to update (optional; defaults to master)

logo_url: https://klekee.netlify.app/images/logo.png
media_folder: static/images
public_folder: /images
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "readTime", name: "readTime", widget: "string"}
      - { label: "tranding" , name: "tranding", widget: "string" }
      - { label: "featured" , name: "featured", widget: "string" }
      - { label: "thumbnail", name: "thumbnail", widget: "image"}
      - { label: "featureImage",name: "featureImage",  widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }
      
    
